### ISSUE TITLE
gene names are not shown when using ds.edgeR and ds.DESeq

### ISSUE THREAD

**Issue by tombisho** [isglobal-brge/dsOmicsClient#17]
When doing differential gene expression with ds.limma(), the results have the gene names as a column. This doesn't seem to be the case when running the following:

````
builder <- newDSLoginBuilder()
builder$append(server = "study1", url = "https://opal-demo.obiba.org", 
               user = "dsuser", password = "password", 
               resource = "RSRC.tcga_liver", driver = "OpalDriver")

logindata <- builder$build()

conns <- datashield.login(logins = logindata, assign = TRUE, 
                          symbol = "res")

datashield.assign.expr(conns = conns, symbol = "rse", expr = quote(as.resource.object(res)))

edger_ds = ds.edgeR(model = ~ gdc_cases.demographic.gender, set = "rse", test = "LRT", normalization = "none")
deseq_ds = ds.DESeq2(model = ~ gdc_cases.demographic.gender, set = "rse")
````
This makes it hard to interpret the results!
but maybe I am doing something wrong!?

**Comment by tombisho** [comment]
I think it is to do with the conversion to a tibble at the end of the serverside function - it removes the row names

**Comment by isglobal-brge** [comment]
yes ... I guess that's the problem. Xavier is going to fix it in a second

**Comment by ESCRI11** [comment]
Issue solved on commits in dsOmics (server package)
https://github.com/isglobal-brge/dsOmics/commit/3ab1dfbaa86c64716804e78c25ca823992d511c0
https://github.com/isglobal-brge/dsOmics/commit/90b7f014a955400cbe1cca5abe79cbb72838aee2

**Comment by tombisho** [comment]
Great - thanks for the quick response!
